### ISSUE TITLE
mass update 

### ISSUE THREAD

**Issue by gregorygermain** [Ouest-France/querydsl-postgrest#11]
### Requested feature

currently, the repo returns the list of elements modified when we are using upsert(), patch(), delete().
we need to only know the number of modified elements.

example of usage :
 long numberOfDeleted = delete(myFirstCriteria);
 long numberOfPatched = patch(mySecondCriteria);
 long numberOfUpdated = upsert(myThirdCriteria);

**Comment by arnaud-thorel-of** [comment]
Fix by #20
