### ISSUE TITLE
search with iterator

### ISSUE THREAD

**Issue by gregorygermain** [Ouest-France/querydsl-postgrest#14]
### Requested feature
The library implements the start of an iterator design pattern via the Page.hasNext() method but data recovery is done via Page.getPageable().next(), which complicates consumption (chaining or recursion).

### Proposal
To implement Page.next() which returns the next page as long as Page.hasNext() returns true.

**Comment by arnaud-thorel-of** [comment]
Page.next require to know the search context to retrieve the nextpage

```java
while(pageable.hasNext()){
  Page<T> result = search(criteria, pageable.next())
  // Do something
  pageable = result.getPageable().next()
}
```

Page.next() may conduct to misunderstanding because Page.next() may return the nextPage
```java
while(page.hasNext()){
  Page<T> result = page.next();
  // Do something;
}
```
