### ISSUE TITLE
Fix : header Prefer count

### ISSUE THREAD

**Issue by anthony-frage-ouest-france** [Ouest-France/querydsl-postgrest#18]
## Description
For the count header key is "Prefer"
https://postgrest.org/en/v10.0/api.html?highlight=pagination#exact-count

But in lib is "Prefers" 

`headers.computeIfAbsent("Prefers", x -> new ArrayList<>())
                    .add("count=" + annotation.countStrategy().name().toLowerCase());`

**Comment by arnaud-thorel-of** [comment]
Fix by #19
