### ISSUE TITLE
Create an adpater to use RestTemplate

### ISSUE THREAD

**Issue by antoinebesnardof** [Ouest-France/querydsl-postgrest#2]
## Current implementation
The default implementation of PostgrestRepository is backed by WebClient of Spring Framework. 

## Requested feature

We need an implementation which uses RestTemplate as backend.

## Proposal

* Create a maven mobule by backend implementation.
* Import each module as optional dependency in the parent pom.

**Comment by arnaud-thorel-of** [comment]
Added to 1.2.2

**Comment by arnaud-thorel-of** [comment]
Added to 1.2.2 version
