### ISSUE TITLE
Inclusion null value in criteria

### ISSUE THREAD

**Issue by anthony-frage-ouest-france** [Ouest-France/querydsl-postgrest#4]
## Current implementation
The "null" values are ignore in criteria
## Requested feature
Take nulls into account in criteria
## Proposal
+ Annotate field in criteria for "null" value not be ignored

**Comment by arnaud-thorel-of** [comment]
see #31

**Comment by arnaud-thorel-of** [comment]
Fix in 1.3.4 @anthony-frage-ouest-france
