### ISSUE TITLE
add on_conflict for upsert

### ISSUE THREAD

**Issue by anthony-frage-ouest-france** [Ouest-France/querydsl-postgrest#8]
## Requested feature
We need to use "on_conflict" parameter for upsert.
Like this: https://postgrest.org/en/v10.0/api.html?highlight=merge#on-conflict

## Proposal
+ Use specific annotation in Criteria
+ Use specific annotation in Repository

**Comment by arnaud-thorel-of** [comment]
Create @OnConflict annotation that allow to be in the both with prior Criteria > Repository
